// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.resourcehealth.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.resourcehealth.ResourcehealthManager;
import com.azure.resourcemanager.resourcehealth.fluent.PotentialOutagesClient;
import com.azure.resourcemanager.resourcehealth.fluent.models.PotentialoutageInner;
import com.azure.resourcemanager.resourcehealth.models.PotentialOutages;
import com.azure.resourcemanager.resourcehealth.models.Potentialoutage;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class PotentialOutagesImpl implements PotentialOutages {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(PotentialOutagesImpl.class);

    private final PotentialOutagesClient innerClient;

    private final ResourcehealthManager serviceManager;

    public PotentialOutagesImpl(PotentialOutagesClient innerClient, ResourcehealthManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public Potentialoutage get() {
        PotentialoutageInner inner = this.serviceClient().get();
        if (inner != null) {
            return new PotentialoutageImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Response<Potentialoutage> getWithResponse(Context context) {
        Response<PotentialoutageInner> inner = this.serviceClient().getWithResponse(context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new PotentialoutageImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public PagedIterable<Potentialoutage> list() {
        PagedIterable<PotentialoutageInner> inner = this.serviceClient().list();
        return inner.mapPage(inner1 -> new PotentialoutageImpl(inner1, this.manager()));
    }

    public PagedIterable<Potentialoutage> list(Context context) {
        PagedIterable<PotentialoutageInner> inner = this.serviceClient().list(context);
        return inner.mapPage(inner1 -> new PotentialoutageImpl(inner1, this.manager()));
    }

    private PotentialOutagesClient serviceClient() {
        return this.innerClient;
    }

    private ResourcehealthManager manager() {
        return this.serviceManager;
    }
}
