/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.cosmosdb.v2020_06_01_preview;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Properties of a managed Cassandra data center on a GET request.
 */
public class DataCenterGetOnlyProperties {
    /**
     * IP addresses for seed nodes in this data center.
     */
    @JsonProperty(value = "seedNodes")
    private List<String> seedNodes;

    /**
     * Get iP addresses for seed nodes in this data center.
     *
     * @return the seedNodes value
     */
    public List<String> seedNodes() {
        return this.seedNodes;
    }

    /**
     * Set iP addresses for seed nodes in this data center.
     *
     * @param seedNodes the seedNodes value to set
     * @return the DataCenterGetOnlyProperties object itself.
     */
    public DataCenterGetOnlyProperties withSeedNodes(List<String> seedNodes) {
        this.seedNodes = seedNodes;
        return this;
    }

}
