// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybridcompute.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;

/** The machine extension instance view. */
@Immutable
public final class MachineExtensionPropertiesInstanceView extends MachineExtensionInstanceView {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(MachineExtensionPropertiesInstanceView.class);

    /** {@inheritDoc} */
    @Override
    public MachineExtensionPropertiesInstanceView withName(String name) {
        super.withName(name);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public MachineExtensionPropertiesInstanceView withType(String type) {
        super.withType(type);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public MachineExtensionPropertiesInstanceView withTypeHandlerVersion(String typeHandlerVersion) {
        super.withTypeHandlerVersion(typeHandlerVersion);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public MachineExtensionPropertiesInstanceView withStatus(MachineExtensionInstanceViewStatus status) {
        super.withStatus(status);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
