/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.postgresql.v2020_10_05_privatepreview;

import com.microsoft.azure.arm.model.HasInner;
import com.microsoft.azure.arm.resources.models.HasManager;
import com.microsoft.azure.management.postgresql.v2020_10_05_privatepreview.implementation.DBForPostgreSqlManager;
import com.microsoft.azure.management.postgresql.v2020_10_05_privatepreview.implementation.ServerGroupConfigurationInner;
import java.util.List;

/**
 * Type representing ServerGroupConfiguration.
 */
public interface ServerGroupConfiguration extends HasInner<ServerGroupConfigurationInner>, HasManager<DBForPostgreSqlManager> {
    /**
     * @return the allowedValues value.
     */
    String allowedValues();

    /**
     * @return the dataType value.
     */
    ConfigurationDataType dataType();

    /**
     * @return the description value.
     */
    String description();

    /**
     * @return the id value.
     */
    String id();

    /**
     * @return the name value.
     */
    String name();

    /**
     * @return the serverRoleGroupConfigurationValues value.
     */
    List<ServerRoleGroupConfigurationValue> serverRoleGroupConfigurationValues();

    /**
     * @return the type value.
     */
    String type();

}
