# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - master
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/marketplacenotifications/

pr:
  branches:
    include:
      - master
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/marketplacenotifications/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: marketplacenotifications
    Artifacts:
      - name: azure-resourcemanager-marketplacenotifications
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermarketplacenotifications
