/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.storage.v2019_06_01.implementation;

import java.util.List;
import com.microsoft.azure.management.storage.v2019_06_01.ListQueue;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Response schema. Contains list of queues returned.
 */
public class ListQueueResourceInner {
    /**
     * List of queues returned.
     */
    @JsonProperty(value = "value", access = JsonProperty.Access.WRITE_ONLY)
    private List<ListQueue> value;

    /**
     * Request URL that can be used to list next page of queues.
     */
    @JsonProperty(value = "nextLink", access = JsonProperty.Access.WRITE_ONLY)
    private String nextLink;

    /**
     * Get list of queues returned.
     *
     * @return the value value
     */
    public List<ListQueue> value() {
        return this.value;
    }

    /**
     * Get request URL that can be used to list next page of queues.
     *
     * @return the nextLink value
     */
    public String nextLink() {
        return this.nextLink;
    }

}
