/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.datafactory.v2018_06_01.implementation;

import com.microsoft.azure.management.datafactory.v2018_06_01.PrivateEndpointConnectionResource;
import com.microsoft.azure.arm.model.implementation.WrapperImpl;
import rx.Observable;
import com.microsoft.azure.management.datafactory.v2018_06_01.RemotePrivateEndpointConnection;

class PrivateEndpointConnectionResourceImpl extends WrapperImpl<PrivateEndpointConnectionResourceInner> implements PrivateEndpointConnectionResource {
    private final DataFactoryManager manager;

    PrivateEndpointConnectionResourceImpl(PrivateEndpointConnectionResourceInner inner,  DataFactoryManager manager) {
        super(inner);
        this.manager = manager;
    }

    @Override
    public DataFactoryManager manager() {
        return this.manager;
    }



    @Override
    public String etag() {
        return this.inner().etag();
    }

    @Override
    public String id() {
        return this.inner().id();
    }

    @Override
    public String name() {
        return this.inner().name();
    }

    @Override
    public RemotePrivateEndpointConnection properties() {
        return this.inner().properties();
    }

    @Override
    public String type() {
        return this.inner().type();
    }

}
