/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.cosmosdb.v2020_06_01_preview.implementation;

import com.microsoft.azure.management.cosmosdb.v2020_06_01_preview.RestorableSqlDatabaseGetResult;
import com.microsoft.azure.arm.model.implementation.IndexableRefreshableWrapperImpl;
import rx.Observable;
import com.microsoft.azure.management.cosmosdb.v2020_06_01_preview.ManagedServiceIdentity;
import com.microsoft.azure.management.cosmosdb.v2020_06_01_preview.RestorableSqlDatabasePropertiesResource;
import java.util.Map;

class RestorableSqlDatabaseGetResultImpl extends IndexableRefreshableWrapperImpl<RestorableSqlDatabaseGetResult, RestorableSqlDatabaseGetResultInner> implements RestorableSqlDatabaseGetResult {
    private final CosmosDBManager manager;
    private String location;
    private String instanceId;
    private String restorableSqlDatabaseId;

    RestorableSqlDatabaseGetResultImpl(RestorableSqlDatabaseGetResultInner inner,  CosmosDBManager manager) {
        super(null, inner);
        this.manager = manager;
        // set resource ancestor and positional variables
        this.location = IdParsingUtils.getValueFromIdByName(inner.id(), "locations");
        this.instanceId = IdParsingUtils.getValueFromIdByName(inner.id(), "restorableDatabaseAccounts");
        this.restorableSqlDatabaseId = IdParsingUtils.getValueFromIdByName(inner.id(), "restorableSqlDatabases");
    }

    @Override
    public CosmosDBManager manager() {
        return this.manager;
    }

    @Override
    protected Observable<RestorableSqlDatabaseGetResultInner> getInnerAsync() {
        RestorableSqlDatabasesInner client = this.manager().inner().restorableSqlDatabases();
        return client.getAsync(this.location, this.instanceId, this.restorableSqlDatabaseId);
    }



    @Override
    public String id() {
        return this.inner().id();
    }

    @Override
    public ManagedServiceIdentity identity() {
        return this.inner().identity();
    }

    @Override
    public String location() {
        return this.inner().location();
    }

    @Override
    public String name() {
        return this.inner().name();
    }

    @Override
    public RestorableSqlDatabasePropertiesResource resource() {
        return this.inner().resource();
    }

    @Override
    public Map<String, String> tags() {
        return this.inner().getTags();
    }

    @Override
    public String type() {
        return this.inner().type();
    }

}
