// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.providerhub.implementation;

import com.azure.resourcemanager.providerhub.ProviderhubManager;
import com.azure.resourcemanager.providerhub.fluent.models.ProviderRegistrationArrayResponseWithContinuationAutoGeneratedInner;
import com.azure.resourcemanager.providerhub.fluent.models.ProviderRegistrationAutoGeneratedInner;
import com.azure.resourcemanager.providerhub.models.ProviderRegistrationArrayResponseWithContinuationAutoGenerated;
import com.azure.resourcemanager.providerhub.models.ProviderRegistrationAutoGenerated;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public final class ProviderRegistrationArrayResponseWithContinuationAutoGeneratedImpl
    implements ProviderRegistrationArrayResponseWithContinuationAutoGenerated {
    private ProviderRegistrationArrayResponseWithContinuationAutoGeneratedInner innerObject;

    private final ProviderhubManager serviceManager;

    ProviderRegistrationArrayResponseWithContinuationAutoGeneratedImpl(
        ProviderRegistrationArrayResponseWithContinuationAutoGeneratedInner innerObject,
        ProviderhubManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<ProviderRegistrationAutoGenerated> value() {
        List<ProviderRegistrationAutoGeneratedInner> inner = this.innerModel().value();
        if (inner != null) {
            return Collections
                .unmodifiableList(
                    inner
                        .stream()
                        .map(inner1 -> new ProviderRegistrationAutoGeneratedImpl(inner1, this.manager()))
                        .collect(Collectors.toList()));
        } else {
            return Collections.emptyList();
        }
    }

    public String nextLink() {
        return this.innerModel().nextLink();
    }

    public ProviderRegistrationArrayResponseWithContinuationAutoGeneratedInner innerModel() {
        return this.innerObject;
    }

    private ProviderhubManager manager() {
        return this.serviceManager;
    }
}
