// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.providerhub.models;

import com.azure.resourcemanager.providerhub.fluent.models.DefaultRolloutPropertiesInner;

/** An immutable client-side representation of DefaultRolloutProperties. */
public interface DefaultRolloutProperties {
    /**
     * Gets the provisioningState property: The provisioningState property.
     *
     * @return the provisioningState value.
     */
    ProvisioningState provisioningState();

    /**
     * Gets the specification property: The specification property.
     *
     * @return the specification value.
     */
    DefaultRolloutSpecification specification();

    /**
     * Gets the status property: The status property.
     *
     * @return the status value.
     */
    DefaultRolloutStatus status();

    /**
     * Gets the inner com.azure.resourcemanager.providerhub.fluent.models.DefaultRolloutPropertiesInner object.
     *
     * @return the inner object.
     */
    DefaultRolloutPropertiesInner innerModel();
}
pecification(specification);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public DefaultRolloutProperties withStatus(DefaultRolloutStatus status) {
        super.withStatus(status);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
