// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.providerhub.models;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;

/** Resource collection API of NotificationRegistrations. */
public interface NotificationRegistrations {
    /**
     * Gets the notification registration details.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the notification registration details.
     */
    NotificationRegistration get(String providerNamespace, String notificationRegistrationName);

    /**
     * Gets the notification registration details.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the notification registration details.
     */
    Response<NotificationRegistration> getWithResponse(
        String providerNamespace, String notificationRegistrationName, Context context);

    /**
     * Creates or updates a notification registration.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the notification registration definition.
     */
    NotificationRegistration createOrUpdate(String providerNamespace, String notificationRegistrationName);

    /**
     * Creates or updates a notification registration.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the notification registration definition.
     */
    Response<NotificationRegistration> createOrUpdateWithResponse(
        String providerNamespace, String notificationRegistrationName, Context context);

    /**
     * Deletes a notification registration.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void deleteByResourceGroup(String providerNamespace, String notificationRegistrationName);

    /**
     * Deletes a notification registration.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    Response<Void> deleteWithResponse(String providerNamespace, String notificationRegistrationName, Context context);

    /**
     * Gets the list of the notification registrations for the given provider.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of the notification registrations for the given provider.
     */
    PagedIterable<NotificationRegistration> listByProviderRegistration(String providerNamespace);

    /**
     * Gets the list of the notification registrations for the given provider.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of the notification registrations for the given provider.
     */
    PagedIterable<NotificationRegistration> listByProviderRegistration(String providerNamespace, Context context);

    /**
     * Gets the notification registration details.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorAutoGeneratedException thrown if the request is
     *     rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the notification registration details.
     */
    NotificationRegistration get(String providerNamespace, String notificationRegistrationName);

    /**
     * Gets the notification registration details.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorAutoGeneratedException thrown if the request is
     *     rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the notification registration details.
     */
    Response<NotificationRegistration> getWithResponse(
        String providerNamespace, String notificationRegistrationName, Context context);

    /**
     * Creates or updates a notification registration.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorAutoGeneratedException thrown if the request is
     *     rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the notification registration definition.
     */
    NotificationRegistration createOrUpdate(String providerNamespace, String notificationRegistrationName);

    /**
     * Creates or updates a notification registration.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorAutoGeneratedException thrown if the request is
     *     rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the notification registration definition.
     */
    Response<NotificationRegistration> createOrUpdateWithResponse(
        String providerNamespace, String notificationRegistrationName, Context context);

    /**
     * Deletes a notification registration.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorAutoGeneratedException thrown if the request is
     *     rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void delete(String providerNamespace, String notificationRegistrationName);

    /**
     * Deletes a notification registration.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param notificationRegistrationName The notification registration.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorAutoGeneratedException thrown if the request is
     *     rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    Response<Void> deleteWithResponse(String providerNamespace, String notificationRegistrationName, Context context);

    /**
     * Gets the list of the notification registrations for the given provider.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorAutoGeneratedException thrown if the request is
     *     rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of the notification registrations for the given provider.
     */
    PagedIterable<NotificationRegistration> listByProviderRegistration(String providerNamespace);

    /**
     * Gets the list of the notification registrations for the given provider.
     *
     * @param providerNamespace The name of the resource provider hosted within ProviderHub.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.resourcemanager.providerhub.models.ErrorAutoGeneratedException thrown if the request is
     *     rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of the notification registrations for the given provider.
     */
    PagedIterable<NotificationRegistration> listByProviderRegistration(String providerNamespace, Context context);
}
