// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.netapp.implementation;

import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.netapp.fluent.VolumeRestoreStatusClient;
import com.azure.resourcemanager.netapp.fluent.models.RestoreStatusInner;
import com.azure.resourcemanager.netapp.models.RestoreStatus;
import com.azure.resourcemanager.netapp.models.VolumeRestoreStatus;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class VolumeRestoreStatusImpl implements VolumeRestoreStatus {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(VolumeRestoreStatusImpl.class);

    private final VolumeRestoreStatusClient innerClient;

    private final com.azure.resourcemanager.netapp.NetAppFilesManager serviceManager;

    public VolumeRestoreStatusImpl(
        VolumeRestoreStatusClient innerClient, com.azure.resourcemanager.netapp.NetAppFilesManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public RestoreStatus get(String resourceGroupName, String accountName, String poolName, String volumeName) {
        RestoreStatusInner inner = this.serviceClient().get(resourceGroupName, accountName, poolName, volumeName);
        if (inner != null) {
            return new RestoreStatusImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Response<RestoreStatus> getWithResponse(
        String resourceGroupName, String accountName, String poolName, String volumeName, Context context) {
        Response<RestoreStatusInner> inner =
            this.serviceClient().getWithResponse(resourceGroupName, accountName, poolName, volumeName, context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new RestoreStatusImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    private VolumeRestoreStatusClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.netapp.NetAppFilesManager manager() {
        return this.serviceManager;
    }
}
