/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.hdinsight.job.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SparkStatementRequest model.
 */
public class SparkStatementRequest {
    /**
     * The code property.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * Possible values include: 'spark', 'pyspark', 'sparkr', 'sql'.
     */
    @JsonProperty(value = "kind")
    private SessionJobKind kind;

    /**
     * Get the code value.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the code value.
     *
     * @param code the code value to set
     * @return the SparkStatementRequest object itself.
     */
    public SparkStatementRequest withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get possible values include: 'spark', 'pyspark', 'sparkr', 'sql'.
     *
     * @return the kind value
     */
    public SessionJobKind kind() {
        return this.kind;
    }

    /**
     * Set possible values include: 'spark', 'pyspark', 'sparkr', 'sql'.
     *
     * @param kind the kind value to set
     * @return the SparkStatementRequest object itself.
     */
    public SparkStatementRequest withKind(SessionJobKind kind) {
        this.kind = kind;
        return this;
    }

}
