// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearningservices.implementation;

import com.azure.resourcemanager.machinelearningservices.MachinelearningservicesManager;
import com.azure.resourcemanager.machinelearningservices.fluent.models.InferenceEndpointKeysTrackedResourceInner;
import com.azure.resourcemanager.machinelearningservices.models.InferenceEndpointKeys;
import com.azure.resourcemanager.machinelearningservices.models.InferenceEndpointKeysTrackedResource;
import com.azure.resourcemanager.machinelearningservices.models.ManagedIdentity;
import com.azure.resourcemanager.machinelearningservices.models.SystemData;
import java.util.Collections;
import java.util.Map;

public final class InferenceEndpointKeysTrackedResourceImpl implements InferenceEndpointKeysTrackedResource {
    private InferenceEndpointKeysTrackedResourceInner innerObject;

    private final MachinelearningservicesManager serviceManager;

    InferenceEndpointKeysTrackedResourceImpl(
        InferenceEndpointKeysTrackedResourceInner innerObject, MachinelearningservicesManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String location() {
        return this.innerModel().location();
    }

    public Map<String, String> tags() {
        Map<String, String> inner = this.innerModel().tags();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public ManagedIdentity identity() {
        return this.innerModel().identity();
    }

    public InferenceEndpointKeys properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public InferenceEndpointKeysTrackedResourceInner innerModel() {
        return this.innerObject;
    }

    private MachinelearningservicesManager manager() {
        return this.serviceManager;
    }
}
