// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearningservices.implementation;

import com.azure.core.management.Region;
import com.azure.core.util.Context;
import com.azure.resourcemanager.machinelearningservices.MachinelearningservicesManager;
import com.azure.resourcemanager.machinelearningservices.fluent.models.OnlineDeploymentPropertiesTrackedResourceInner;
import com.azure.resourcemanager.machinelearningservices.models.ManagedIdentity;
import com.azure.resourcemanager.machinelearningservices.models.OnlineDeploymentProperties;
import com.azure.resourcemanager.machinelearningservices.models.OnlineDeploymentPropertiesTrackedResource;
import com.azure.resourcemanager.machinelearningservices.models.SystemData;
import java.util.Collections;
import java.util.Map;

public final class OnlineDeploymentPropertiesTrackedResourceImpl
    implements OnlineDeploymentPropertiesTrackedResource,
        OnlineDeploymentPropertiesTrackedResource.Definition,
        OnlineDeploymentPropertiesTrackedResource.Update {
    private OnlineDeploymentPropertiesTrackedResourceInner innerObject;

    private final MachinelearningservicesManager serviceManager;

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String location() {
        return this.innerModel().location();
    }

    public Map<String, String> tags() {
        Map<String, String> inner = this.innerModel().tags();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public ManagedIdentity identity() {
        return this.innerModel().identity();
    }

    public OnlineDeploymentProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public Region region() {
        return Region.fromName(this.regionName());
    }

    public String regionName() {
        return this.location();
    }

    public OnlineDeploymentPropertiesTrackedResourceInner innerModel() {
        return this.innerObject;
    }

    private MachinelearningservicesManager manager() {
        return this.serviceManager;
    }

    private String endpointName;

    private String deploymentName;

    private String resourceGroupName;

    private String workspaceName;

    public OnlineDeploymentPropertiesTrackedResourceImpl withExistingOnlineEndpoint(
        String endpointName, String resourceGroupName, String workspaceName) {
        this.endpointName = endpointName;
        this.resourceGroupName = resourceGroupName;
        this.workspaceName = workspaceName;
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResource create() {
        this.innerObject =
            serviceManager
                .serviceClient()
                .getOnlineDeployments()
                .createOrUpdateWithResponse(
                    endpointName, deploymentName, resourceGroupName, workspaceName, this.innerModel(), Context.NONE)
                .getValue();
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResource create(Context context) {
        this.innerObject =
            serviceManager
                .serviceClient()
                .getOnlineDeployments()
                .createOrUpdateWithResponse(
                    endpointName, deploymentName, resourceGroupName, workspaceName, this.innerModel(), context)
                .getValue();
        return this;
    }

    OnlineDeploymentPropertiesTrackedResourceImpl(String name, MachinelearningservicesManager serviceManager) {
        this.innerObject = new OnlineDeploymentPropertiesTrackedResourceInner();
        this.serviceManager = serviceManager;
        this.deploymentName = name;
    }

    public OnlineDeploymentPropertiesTrackedResourceImpl update() {
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResource apply() {
        this.innerObject =
            serviceManager
                .serviceClient()
                .getOnlineDeployments()
                .createOrUpdateWithResponse(
                    endpointName, deploymentName, resourceGroupName, workspaceName, this.innerModel(), Context.NONE)
                .getValue();
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResource apply(Context context) {
        this.innerObject =
            serviceManager
                .serviceClient()
                .getOnlineDeployments()
                .createOrUpdateWithResponse(
                    endpointName, deploymentName, resourceGroupName, workspaceName, this.innerModel(), context)
                .getValue();
        return this;
    }

    OnlineDeploymentPropertiesTrackedResourceImpl(
        OnlineDeploymentPropertiesTrackedResourceInner innerObject, MachinelearningservicesManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
        this.endpointName = Utils.getValueFromIdByName(innerObject.id(), "onlineEndpoints");
        this.deploymentName = Utils.getValueFromIdByName(innerObject.id(), "deployments");
        this.resourceGroupName = Utils.getValueFromIdByName(innerObject.id(), "resourceGroups");
        this.workspaceName = Utils.getValueFromIdByName(innerObject.id(), "workspaces");
    }

    public OnlineDeploymentPropertiesTrackedResource refresh() {
        this.innerObject =
            serviceManager
                .serviceClient()
                .getOnlineDeployments()
                .getWithResponse(endpointName, deploymentName, resourceGroupName, workspaceName, Context.NONE)
                .getValue();
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResource refresh(Context context) {
        this.innerObject =
            serviceManager
                .serviceClient()
                .getOnlineDeployments()
                .getWithResponse(endpointName, deploymentName, resourceGroupName, workspaceName, context)
                .getValue();
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResourceImpl withRegion(Region location) {
        this.innerModel().withLocation(location.toString());
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResourceImpl withRegion(String location) {
        this.innerModel().withLocation(location);
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResourceImpl withProperties(OnlineDeploymentProperties properties) {
        this.innerModel().withProperties(properties);
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResourceImpl withTags(Map<String, String> tags) {
        this.innerModel().withTags(tags);
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResourceImpl withKind(String kind) {
        this.innerModel().withKind(kind);
        return this;
    }

    public OnlineDeploymentPropertiesTrackedResourceImpl withIdentity(ManagedIdentity identity) {
        this.innerModel().withIdentity(identity);
        return this;
    }
}
