// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.datalakestore.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Data Lake Store inner error information. */
@Immutable
public final class InnerError {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(InnerError.class);

    /*
     * the stack trace for the error
     */
    @JsonProperty(value = "trace", access = JsonProperty.Access.WRITE_ONLY)
    private String trace;

    /*
     * the context for the error message
     */
    @JsonProperty(value = "context", access = JsonProperty.Access.WRITE_ONLY)
    private String context;

    /**
     * Get the trace property: the stack trace for the error.
     *
     * @return the trace value.
     */
    public String trace() {
        return this.trace;
    }

    /**
     * Get the context property: the context for the error message.
     *
     * @return the context value.
     */
    public String context() {
        return this.context;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
