/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.policyinsights.v2020_07_01;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The restrictions on a field imposed by a specific policy.
 */
public class FieldRestriction {
    /**
     * The type of restriction that is imposed on the field. Possible values
     * include: 'Required', 'Removed', 'Deny'.
     */
    @JsonProperty(value = "result", access = JsonProperty.Access.WRITE_ONLY)
    private FieldRestrictionResult result;

    /**
     * The value that policy will set for the field if the user does not
     * provide a value.
     */
    @JsonProperty(value = "defaultValue", access = JsonProperty.Access.WRITE_ONLY)
    private String defaultValue;

    /**
     * The values that policy either requires or denies for the field.
     */
    @JsonProperty(value = "values", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> values;

    /**
     * The details of the policy that is causing the field restriction.
     */
    @JsonProperty(value = "policy", access = JsonProperty.Access.WRITE_ONLY)
    private PolicyReference policy;

    /**
     * Get the type of restriction that is imposed on the field. Possible values include: 'Required', 'Removed', 'Deny'.
     *
     * @return the result value
     */
    public FieldRestrictionResult result() {
        return this.result;
    }

    /**
     * Get the value that policy will set for the field if the user does not provide a value.
     *
     * @return the defaultValue value
     */
    public String defaultValue() {
        return this.defaultValue;
    }

    /**
     * Get the values that policy either requires or denies for the field.
     *
     * @return the values value
     */
    public List<String> values() {
        return this.values;
    }

    /**
     * Get the details of the policy that is causing the field restriction.
     *
     * @return the policy value
     */
    public PolicyReference policy() {
        return this.policy;
    }

}
