/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.policyinsights.v2020_07_01;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Resource identifiers for a policy.
 */
public class PolicyReference {
    /**
     * The resource identifier of the policy definition.
     */
    @JsonProperty(value = "policyDefinitionId", access = JsonProperty.Access.WRITE_ONLY)
    private String policyDefinitionId;

    /**
     * The resource identifier of the policy set definition.
     */
    @JsonProperty(value = "policySetDefinitionId", access = JsonProperty.Access.WRITE_ONLY)
    private String policySetDefinitionId;

    /**
     * The reference identifier of a specific policy definition within a policy
     * set definition.
     */
    @JsonProperty(value = "policyDefinitionReferenceId", access = JsonProperty.Access.WRITE_ONLY)
    private String policyDefinitionReferenceId;

    /**
     * The resource identifier of the policy assignment.
     */
    @JsonProperty(value = "policyAssignmentId", access = JsonProperty.Access.WRITE_ONLY)
    private String policyAssignmentId;

    /**
     * Get the resource identifier of the policy definition.
     *
     * @return the policyDefinitionId value
     */
    public String policyDefinitionId() {
        return this.policyDefinitionId;
    }

    /**
     * Get the resource identifier of the policy set definition.
     *
     * @return the policySetDefinitionId value
     */
    public String policySetDefinitionId() {
        return this.policySetDefinitionId;
    }

    /**
     * Get the reference identifier of a specific policy definition within a policy set definition.
     *
     * @return the policyDefinitionReferenceId value
     */
    public String policyDefinitionReferenceId() {
        return this.policyDefinitionReferenceId;
    }

    /**
     * Get the resource identifier of the policy assignment.
     *
     * @return the policyAssignmentId value
     */
    public String policyAssignmentId() {
        return this.policyAssignmentId;
    }

}
