// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.healthbot.implementation;

import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.healthbot.HealthbotManager;
import com.azure.resourcemanager.healthbot.fluent.GetsClient;
import com.azure.resourcemanager.healthbot.fluent.models.HealthBotInner;
import com.azure.resourcemanager.healthbot.models.Gets;
import com.azure.resourcemanager.healthbot.models.HealthBot;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class GetsImpl implements Gets {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(GetsImpl.class);

    private final GetsClient innerClient;

    private final HealthbotManager serviceManager;

    public GetsImpl(GetsClient innerClient, HealthbotManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public HealthBot getByResourceGroup(String resourceGroupName, String resourceName) {
        HealthBotInner inner = this.serviceClient().getByResourceGroup(resourceGroupName, resourceName);
        if (inner != null) {
            return new HealthBotImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Response<HealthBot> getByResourceGroupWithResponse(
        String resourceGroupName, String resourceName, Context context) {
        Response<HealthBotInner> inner =
            this.serviceClient().getByResourceGroupWithResponse(resourceGroupName, resourceName, context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new HealthBotImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    private GetsClient serviceClient() {
        return this.innerClient;
    }

    private HealthbotManager manager() {
        return this.serviceManager;
    }
}
