// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.kubernetesconfiguration.fluent.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.annotation.JsonFlatten;
import com.azure.core.management.SystemData;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.kubernetesconfiguration.models.ClusterTypes;
import com.azure.resourcemanager.kubernetesconfiguration.models.SupportedScopes;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Represents an Extension Type. */
@JsonFlatten
@Immutable
public class ExtensionTypeInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(ExtensionTypeInner.class);

    /*
     * Metadata pertaining to creation and last modification of the resource.
     */
    @JsonProperty(value = "systemData", access = JsonProperty.Access.WRITE_ONLY)
    private SystemData systemData;

    /*
     * Extension release train: preview or stable
     */
    @JsonProperty(value = "properties.releaseTrains", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> releaseTrains;

    /*
     * Cluster types
     */
    @JsonProperty(value = "properties.clusterTypes", access = JsonProperty.Access.WRITE_ONLY)
    private ClusterTypes clusterTypes;

    /*
     * Extension scopes
     */
    @JsonProperty(value = "properties.supportedScopes", access = JsonProperty.Access.WRITE_ONLY)
    private SupportedScopes supportedScopes;

    /**
     * Get the systemData property: Metadata pertaining to creation and last modification of the resource.
     *
     * @return the systemData value.
     */
    public SystemData systemData() {
        return this.systemData;
    }

    /**
     * Get the releaseTrains property: Extension release train: preview or stable.
     *
     * @return the releaseTrains value.
     */
    public List<String> releaseTrains() {
        return this.releaseTrains;
    }

    /**
     * Get the clusterTypes property: Cluster types.
     *
     * @return the clusterTypes value.
     */
    public ClusterTypes clusterTypes() {
        return this.clusterTypes;
    }

    /**
     * Get the supportedScopes property: Extension scopes.
     *
     * @return the supportedScopes value.
     */
    public SupportedScopes supportedScopes() {
        return this.supportedScopes;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (supportedScopes() != null) {
            supportedScopes().validate();
        }
    }
}
