// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.managedservices.models;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;
import com.azure.resourcemanager.managedservices.fluent.models.RegistrationDefinitionInner;

/** Resource collection API of RegistrationDefinitions. */
public interface RegistrationDefinitions {
    /**
     * Gets the registration definition details.
     *
     * @param scope Scope of the resource.
     * @param registrationDefinitionId Guid of the registration definition.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the registration definition details.
     */
    RegistrationDefinition get(String scope, String registrationDefinitionId);

    /**
     * Gets the registration definition details.
     *
     * @param scope Scope of the resource.
     * @param registrationDefinitionId Guid of the registration definition.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the registration definition details.
     */
    Response<RegistrationDefinition> getWithResponse(String scope, String registrationDefinitionId, Context context);

    /**
     * Deletes the registration definition.
     *
     * @param registrationDefinitionId Guid of the registration definition.
     * @param scope Scope of the resource.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void delete(String registrationDefinitionId, String scope);

    /**
     * Deletes the registration definition.
     *
     * @param registrationDefinitionId Guid of the registration definition.
     * @param scope Scope of the resource.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    Response<Void> deleteWithResponse(String registrationDefinitionId, String scope, Context context);

    /**
     * Creates or updates a registration definition.
     *
     * @param registrationDefinitionId Guid of the registration definition.
     * @param scope Scope of the resource.
     * @param requestBody Registration definition.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return registration definition.
     */
    RegistrationDefinition createOrUpdate(
        String registrationDefinitionId, String scope, RegistrationDefinitionInner requestBody);

    /**
     * Creates or updates a registration definition.
     *
     * @param registrationDefinitionId Guid of the registration definition.
     * @param scope Scope of the resource.
     * @param requestBody Registration definition.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return registration definition.
     */
    RegistrationDefinition createOrUpdate(
        String registrationDefinitionId, String scope, RegistrationDefinitionInner requestBody, Context context);

    /**
     * Gets a list of the registration definitions.
     *
     * @param scope Scope of the resource.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a list of the registration definitions.
     */
    PagedIterable<RegistrationDefinition> list(String scope);

    /**
     * Gets a list of the registration definitions.
     *
     * @param scope Scope of the resource.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a list of the registration definitions.
     */
    PagedIterable<RegistrationDefinition> list(String scope, Context context);
}
