/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.storagecache.v2020_03_01;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Force GSI Properties.
 */
public class ForceGsiProperties {
    /**
     * The comment associated with the GSI.
     */
    @JsonProperty(value = "comment")
    private String comment;

    /**
     * Get the comment associated with the GSI.
     *
     * @return the comment value
     */
    public String comment() {
        return this.comment;
    }

    /**
     * Set the comment associated with the GSI.
     *
     * @param comment the comment value to set
     * @return the ForceGsiProperties object itself.
     */
    public ForceGsiProperties withComment(String comment) {
        this.comment = comment;
        return this;
    }

}
