// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.desktopvirtualization.models;

import com.azure.core.management.SystemData;
import com.azure.resourcemanager.desktopvirtualization.fluent.models.SessionHostConfigurationInner;
import java.time.OffsetDateTime;

/** An immutable client-side representation of SessionHostConfiguration. */
public interface SessionHostConfiguration {
    /**
     * Gets the id property: Fully qualified resource Id for the resource.
     *
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: The name of the resource.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: The type of the resource.
     *
     * @return the type value.
     */
    String type();

    /**
     * Gets the systemData property: Metadata pertaining to creation and last modification of the resource.
     *
     * @return the systemData value.
     */
    SystemData systemData();

    /**
     * Gets the version property: The time when session host configuration was last modified and something was changed.
     *
     * @return the version value.
     */
    OffsetDateTime version();

    /**
     * Gets the vmSizeId property: The id of the size of a virtual machine connected to a hostpool.
     *
     * @return the vmSizeId value.
     */
    String vmSizeId();

    /**
     * Gets the diskType property: The disk type used by virtual machine in hostpool session host.
     *
     * @return the diskType value.
     */
    VirtualMachineDiskType diskType();

    /**
     * Gets the vmCustomConfigurationUri property: The uri to the storage blob containing the arm template to be run on
     * the virtual machine after provisioning.
     *
     * @return the vmCustomConfigurationUri value.
     */
    String vmCustomConfigurationUri();

    /**
     * Gets the vmCustomConfigurationParameterUri property: The uri to the storage blob containing the parameter file to
     * be run on the virtual machine after provisioning.
     *
     * @return the vmCustomConfigurationParameterUri value.
     */
    String vmCustomConfigurationParameterUri();

    /**
     * Gets the imageInfo property: Image configurations of HostPool.
     *
     * @return the imageInfo value.
     */
    ImageInfoProperties imageInfo();

    /**
     * Gets the domainInfo property: Domain configurations of session hosts.
     *
     * @return the domainInfo value.
     */
    DomainInfoProperties domainInfo();

    /**
     * Gets the inner com.azure.resourcemanager.desktopvirtualization.fluent.models.SessionHostConfigurationInner
     * object.
     *
     * @return the inner object.
     */
    SessionHostConfigurationInner innerModel();
}
