// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearningservices.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for EndpointComputeType. */
public final class EndpointComputeType extends ExpandableStringEnum<EndpointComputeType> {
    /** Static value Managed for EndpointComputeType. */
    public static final EndpointComputeType MANAGED = fromString("Managed");

    /** Static value AKS for EndpointComputeType. */
    public static final EndpointComputeType AKS = fromString("AKS");

    /** Static value AzureMLCompute for EndpointComputeType. */
    public static final EndpointComputeType AZURE_MLCOMPUTE = fromString("AzureMLCompute");

    /**
     * Creates or finds a EndpointComputeType from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding EndpointComputeType.
     */
    @JsonCreator
    public static EndpointComputeType fromString(String name) {
        return fromString(name, EndpointComputeType.class);
    }

    /** @return known EndpointComputeType values. */
    public static Collection<EndpointComputeType> values() {
        return values(EndpointComputeType.class);
    }
}
