// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearningservices.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The InferenceEndpointKeys model. */
@Fluent
public final class InferenceEndpointKeys {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(InferenceEndpointKeys.class);

    /*
     * Endpoint keys
     */
    @JsonProperty(value = "endpointKey")
    private String endpointKey;

    /**
     * Get the endpointKey property: Endpoint keys.
     *
     * @return the endpointKey value.
     */
    public String endpointKey() {
        return this.endpointKey;
    }

    /**
     * Set the endpointKey property: Endpoint keys.
     *
     * @param endpointKey the endpointKey value to set.
     * @return the InferenceEndpointKeys object itself.
     */
    public InferenceEndpointKeys withEndpointKey(String endpointKey) {
        this.endpointKey = endpointKey;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
