// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearningservices.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for LabelExportState. */
public final class LabelExportState extends ExpandableStringEnum<LabelExportState> {
    /** Static value Requested for LabelExportState. */
    public static final LabelExportState REQUESTED = fromString("Requested");

    /** Static value Running for LabelExportState. */
    public static final LabelExportState RUNNING = fromString("Running");

    /** Static value Failed for LabelExportState. */
    public static final LabelExportState FAILED = fromString("Failed");

    /** Static value Completed for LabelExportState. */
    public static final LabelExportState COMPLETED = fromString("Completed");

    /**
     * Creates or finds a LabelExportState from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding LabelExportState.
     */
    @JsonCreator
    public static LabelExportState fromString(String name) {
        return fromString(name, LabelExportState.class);
    }

    /** @return known LabelExportState values. */
    public static Collection<LabelExportState> values() {
        return values(LabelExportState.class);
    }
}
