// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearningservices.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** Empty/none datastore credentials. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "credentialsType")
@JsonTypeName("None")
@Fluent
public final class NoneDatastoreCredentials extends DatastoreCredentials {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(NoneDatastoreCredentials.class);

    /*
     * Empty/none datastore secret.
     */
    @JsonProperty(value = "secrets")
    private NoneDatastoreSecrets secrets;

    /**
     * Get the secrets property: Empty/none datastore secret.
     *
     * @return the secrets value.
     */
    public NoneDatastoreSecrets secrets() {
        return this.secrets;
    }

    /**
     * Set the secrets property: Empty/none datastore secret.
     *
     * @param secrets the secrets value to set.
     * @return the NoneDatastoreCredentials object itself.
     */
    public NoneDatastoreCredentials withSecrets(NoneDatastoreSecrets secrets) {
        this.secrets = secrets;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
        if (secrets() != null) {
            secrets().validate();
        }
    }
}
