// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearningservices.models;

import com.azure.core.management.SystemData;
import com.azure.resourcemanager.machinelearningservices.fluent.models.ServiceResourceInner;
import java.util.Map;

/** An immutable client-side representation of ServiceResource. */
public interface ServiceResource {
    /**
     * Gets the properties property: Service properties.
     *
     * @return the properties value.
     */
    ServiceResponseBase properties();

    /**
     * Gets the identity property: The identity of the resource.
     *
     * @return the identity value.
     */
    Identity identity();

    /**
     * Gets the location property: Specifies the location of the resource.
     *
     * @return the location value.
     */
    String location();

    /**
     * Gets the tags property: Contains resource tags defined as key/value pairs.
     *
     * @return the tags value.
     */
    Map<String, String> tags();

    /**
     * Gets the sku property: The sku of the workspace.
     *
     * @return the sku value.
     */
    Sku sku();

    /**
     * Gets the systemData property: System Data.
     *
     * @return the systemData value.
     */
    SystemData systemData();

    /**
     * Gets the inner com.azure.resourcemanager.machinelearningservices.fluent.models.ServiceResourceInner object.
     *
     * @return the inner object.
     */
    ServiceResourceInner innerModel();
}
