/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.appplatform.v2020_11_01_preview;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Monitoring Setting properties payload.
 */
public class MonitoringSettingProperties {
    /**
     * State of the Monitoring Setting. Possible values include:
     * 'NotAvailable', 'Failed', 'Succeeded', 'Updating'.
     */
    @JsonProperty(value = "provisioningState", access = JsonProperty.Access.WRITE_ONLY)
    private MonitoringSettingState provisioningState;

    /**
     * Error when apply Monitoring Setting changes.
     */
    @JsonProperty(value = "error")
    private Error error;

    /**
     * Target application insight instrumentation key.
     */
    @JsonProperty(value = "applicationInsightsInstrumentationKey")
    private String applicationInsightsInstrumentationKey;

    /**
     * Indicates the sampling rate of application insight agent, should be in
     * range [0.0, 100.0].
     */
    @JsonProperty(value = "applicationInsightsSamplingRate")
    private Double applicationInsightsSamplingRate;

    /**
     * Indicates the versions of application insight agent.
     */
    @JsonProperty(value = "applicationInsightsAgentVersions")
    private ApplicationInsightsAgentVersions applicationInsightsAgentVersions;

    /**
     * Get state of the Monitoring Setting. Possible values include: 'NotAvailable', 'Failed', 'Succeeded', 'Updating'.
     *
     * @return the provisioningState value
     */
    public MonitoringSettingState provisioningState() {
        return this.provisioningState;
    }

    /**
     * Get error when apply Monitoring Setting changes.
     *
     * @return the error value
     */
    public Error error() {
        return this.error;
    }

    /**
     * Set error when apply Monitoring Setting changes.
     *
     * @param error the error value to set
     * @return the MonitoringSettingProperties object itself.
     */
    public MonitoringSettingProperties withError(Error error) {
        this.error = error;
        return this;
    }

    /**
     * Get target application insight instrumentation key.
     *
     * @return the applicationInsightsInstrumentationKey value
     */
    public String applicationInsightsInstrumentationKey() {
        return this.applicationInsightsInstrumentationKey;
    }

    /**
     * Set target application insight instrumentation key.
     *
     * @param applicationInsightsInstrumentationKey the applicationInsightsInstrumentationKey value to set
     * @return the MonitoringSettingProperties object itself.
     */
    public MonitoringSettingProperties withApplicationInsightsInstrumentationKey(String applicationInsightsInstrumentationKey) {
        this.applicationInsightsInstrumentationKey = applicationInsightsInstrumentationKey;
        return this;
    }

    /**
     * Get indicates the sampling rate of application insight agent, should be in range [0.0, 100.0].
     *
     * @return the applicationInsightsSamplingRate value
     */
    public Double applicationInsightsSamplingRate() {
        return this.applicationInsightsSamplingRate;
    }

    /**
     * Set indicates the sampling rate of application insight agent, should be in range [0.0, 100.0].
     *
     * @param applicationInsightsSamplingRate the applicationInsightsSamplingRate value to set
     * @return the MonitoringSettingProperties object itself.
     */
    public MonitoringSettingProperties withApplicationInsightsSamplingRate(Double applicationInsightsSamplingRate) {
        this.applicationInsightsSamplingRate = applicationInsightsSamplingRate;
        return this;
    }

    /**
     * Get indicates the versions of application insight agent.
     *
     * @return the applicationInsightsAgentVersions value
     */
    public ApplicationInsightsAgentVersions applicationInsightsAgentVersions() {
        return this.applicationInsightsAgentVersions;
    }

    /**
     * Set indicates the versions of application insight agent.
     *
     * @param applicationInsightsAgentVersions the applicationInsightsAgentVersions value to set
     * @return the MonitoringSettingProperties object itself.
     */
    public MonitoringSettingProperties withApplicationInsightsAgentVersions(ApplicationInsightsAgentVersions applicationInsightsAgentVersions) {
        this.applicationInsightsAgentVersions = applicationInsightsAgentVersions;
        return this;
    }

}
