// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.recoveryservicessiterecovery.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.recoveryservicessiterecovery.SiteRecoveryManager;
import com.azure.resourcemanager.recoveryservicessiterecovery.fluent.ReplicationEventsClient;
import com.azure.resourcemanager.recoveryservicessiterecovery.fluent.models.EventInner;
import com.azure.resourcemanager.recoveryservicessiterecovery.models.Event;
import com.azure.resourcemanager.recoveryservicessiterecovery.models.ReplicationEvents;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class ReplicationEventsImpl implements ReplicationEvents {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(ReplicationEventsImpl.class);

    private final ReplicationEventsClient innerClient;

    private final SiteRecoveryManager serviceManager;

    public ReplicationEventsImpl(ReplicationEventsClient innerClient, SiteRecoveryManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<Event> list() {
        PagedIterable<EventInner> inner = this.serviceClient().list();
        return inner.mapPage(inner1 -> new EventImpl(inner1, this.manager()));
    }

    public PagedIterable<Event> list(String filter, Context context) {
        PagedIterable<EventInner> inner = this.serviceClient().list(filter, context);
        return inner.mapPage(inner1 -> new EventImpl(inner1, this.manager()));
    }

    public Event get(String eventName) {
        EventInner inner = this.serviceClient().get(eventName);
        if (inner != null) {
            return new EventImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Response<Event> getWithResponse(String eventName, Context context) {
        Response<EventInner> inner = this.serviceClient().getWithResponse(eventName, context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new EventImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    private ReplicationEventsClient serviceClient() {
        return this.innerClient;
    }

    private SiteRecoveryManager manager() {
        return this.serviceManager;
    }
}
