// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.avs.models;

import com.azure.resourcemanager.avs.fluent.models.DatastoreInner;

/** An immutable client-side representation of Datastore. */
public interface Datastore {
    /**
     * Gets the id property: Fully qualified resource Id for the resource.
     *
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: The name of the resource.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: The type of the resource.
     *
     * @return the type value.
     */
    String type();

    /**
     * Gets the provisioningState property: The state of the datastore provisioning.
     *
     * @return the provisioningState value.
     */
    DatastoreProvisioningState provisioningState();

    /**
     * Gets the netAppVolume property: Resource ID of the Azure NetApp Files volume.
     *
     * @return the netAppVolume value.
     */
    NetAppVolumeProperties netAppVolume();

    /**
     * Gets the diskPoolVolume property: Resource ID of the iSCSI target from a Storage Pool and LUN to be used.
     *
     * @return the diskPoolVolume value.
     */
    DiskPoolVolumeProperties diskPoolVolume();

    /**
     * Gets the inner com.azure.resourcemanager.avs.fluent.models.DatastoreInner object.
     *
     * @return the inner object.
     */
    DatastoreInner innerModel();
}
