// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.resourcehealth.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for State. */
public final class State extends ExpandableStringEnum<State> {
    /** Static value INVALID for State. */
    public static final State INVALID = fromString("INVALID");

    /** Static value ACTIVE for State. */
    public static final State ACTIVE = fromString("ACTIVE");

    /** Static value RESOLVED for State. */
    public static final State RESOLVED = fromString("RESOLVED");

    /** Static value NEW for State. */
    public static final State NEW = fromString("NEW");

    /** Static value MITIGATING for State. */
    public static final State MITIGATING = fromString("MITIGATING");

    /** Static value CORRELATING for State. */
    public static final State CORRELATING = fromString("CORRELATING");

    /** Static value MITIGATED for State. */
    public static final State MITIGATED = fromString("MITIGATED");

    /** Static value HOLDING for State. */
    public static final State HOLDING = fromString("HOLDING");

    /** Static value SUPPRESSED for State. */
    public static final State SUPPRESSED = fromString("SUPPRESSED");

    /**
     * Creates or finds a State from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding State.
     */
    @JsonCreator
    public static State fromString(String name) {
        return fromString(name, State.class);
    }

    /** @return known State values. */
    public static Collection<State> values() {
        return values(State.class);
    }
}
