/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.billing.v2019_10_01_preview;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The additional specific properties for an event.
 */
public class BillingActivityEventProperties {
    /**
     * Name of the additional property for an event.
     */
    @JsonProperty(value = "name", access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    /**
     * Get name of the additional property for an event.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

}
