/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.billing.v2019_10_01_preview;

import rx.Observable;
import com.microsoft.azure.management.billing.v2019_10_01_preview.implementation.BillingActivityListsInner;
import com.microsoft.azure.arm.model.HasInner;

/**
 * Type representing BillingActivityLists.
 */
public interface BillingActivityLists extends HasInner<BillingActivityListsInner> {
    /**
     * Gets billing activity logs for a billing account.
     *
     * @param billingAccountName The ID that uniquely identifies a billing account.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Observable<BillingActivity> getAsync(final String billingAccountName);

}
