/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.billing.v2019_10_01_preview;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Request parameters to create an account.
 */
public class CreateEnrollmentAccount {
    /**
     * Name of the account.
     */
    @JsonProperty(value = "accountName")
    private String accountName;

    /**
     * Email address of account owner.
     */
    @JsonProperty(value = "accountOwner")
    private String accountOwner;

    /**
     * Type of authentication to be supported. Possible values include:
     * 'MicrosoftAccount', 'WorkOrSchoolAccount'.
     */
    @JsonProperty(value = "authType")
    private AuthType authType;

    /**
     * Cost Center associated to account.
     */
    @JsonProperty(value = "costCenter")
    private String costCenter;

    /**
     * Department Id to which account should be associated.
     */
    @JsonProperty(value = "departmentName")
    private String departmentName;

    /**
     * Get name of the account.
     *
     * @return the accountName value
     */
    public String accountName() {
        return this.accountName;
    }

    /**
     * Set name of the account.
     *
     * @param accountName the accountName value to set
     * @return the CreateEnrollmentAccount object itself.
     */
    public CreateEnrollmentAccount withAccountName(String accountName) {
        this.accountName = accountName;
        return this;
    }

    /**
     * Get email address of account owner.
     *
     * @return the accountOwner value
     */
    public String accountOwner() {
        return this.accountOwner;
    }

    /**
     * Set email address of account owner.
     *
     * @param accountOwner the accountOwner value to set
     * @return the CreateEnrollmentAccount object itself.
     */
    public CreateEnrollmentAccount withAccountOwner(String accountOwner) {
        this.accountOwner = accountOwner;
        return this;
    }

    /**
     * Get type of authentication to be supported. Possible values include: 'MicrosoftAccount', 'WorkOrSchoolAccount'.
     *
     * @return the authType value
     */
    public AuthType authType() {
        return this.authType;
    }

    /**
     * Set type of authentication to be supported. Possible values include: 'MicrosoftAccount', 'WorkOrSchoolAccount'.
     *
     * @param authType the authType value to set
     * @return the CreateEnrollmentAccount object itself.
     */
    public CreateEnrollmentAccount withAuthType(AuthType authType) {
        this.authType = authType;
        return this;
    }

    /**
     * Get cost Center associated to account.
     *
     * @return the costCenter value
     */
    public String costCenter() {
        return this.costCenter;
    }

    /**
     * Set cost Center associated to account.
     *
     * @param costCenter the costCenter value to set
     * @return the CreateEnrollmentAccount object itself.
     */
    public CreateEnrollmentAccount withCostCenter(String costCenter) {
        this.costCenter = costCenter;
        return this;
    }

    /**
     * Get department Id to which account should be associated.
     *
     * @return the departmentName value
     */
    public String departmentName() {
        return this.departmentName;
    }

    /**
     * Set department Id to which account should be associated.
     *
     * @param departmentName the departmentName value to set
     * @return the CreateEnrollmentAccount object itself.
     */
    public CreateEnrollmentAccount withDepartmentName(String departmentName) {
        this.departmentName = departmentName;
        return this;
    }

}
