/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.policyinsights.v2019_10_01.implementation;

import com.microsoft.azure.management.policyinsights.v2019_10_01.ComplianceState;
import org.joda.time.DateTime;
import java.util.List;
import com.microsoft.azure.management.policyinsights.v2019_10_01.AttestationEvidence;
import com.microsoft.azure.management.policyinsights.v2019_10_01.SystemData;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.rest.serializer.JsonFlatten;
import com.microsoft.azure.ProxyResource;

/**
 * An attestation resource.
 */
@JsonFlatten
public class AttestationInner extends ProxyResource {
    /**
     * The resource ID of the policy assignment that the attestation is setting
     * the state for.
     */
    @JsonProperty(value = "properties.policyAssignmentId", required = true)
    private String policyAssignmentId;

    /**
     * The policy definition reference ID from a policy set definition that the
     * attestation is setting the state for. If the policy assignment assigns a
     * policy set definition the attestation can choose a definition within the
     * set definition with this property or omit this and set the state for the
     * entire set definition.
     */
    @JsonProperty(value = "properties.policyDefinitionReferenceId")
    private String policyDefinitionReferenceId;

    /**
     * The compliance state that should be set on the resource. Possible values
     * include: 'Compliant', 'NonCompliant', 'Unknown'.
     */
    @JsonProperty(value = "properties.complianceState")
    private ComplianceState complianceState;

    /**
     * The time the compliance state should expire.
     */
    @JsonProperty(value = "properties.expiresOn")
    private DateTime expiresOn;

    /**
     * The person responsible for setting the state of the resource. This value
     * is typically an Azure Active Directory object ID.
     */
    @JsonProperty(value = "properties.owner")
    private String owner;

    /**
     * Comments describing why this attestation was created.
     */
    @JsonProperty(value = "properties.comments")
    private String comments;

    /**
     * The evidence supporting the compliance state set in this attestation.
     */
    @JsonProperty(value = "properties.evidence")
    private List<AttestationEvidence> evidence;

    /**
     * The status of the attestation.
     */
    @JsonProperty(value = "properties.provisioningState", access = JsonProperty.Access.WRITE_ONLY)
    private String provisioningState;

    /**
     * The time the compliance state was last changed in this attestation.
     */
    @JsonProperty(value = "properties.lastComplianceStateChangeAt", access = JsonProperty.Access.WRITE_ONLY)
    private DateTime lastComplianceStateChangeAt;

    /**
     * Azure Resource Manager metadata containing createdBy and modifiedBy
     * information.
     */
    @JsonProperty(value = "systemData", access = JsonProperty.Access.WRITE_ONLY)
    private SystemData systemData;

    /**
     * Get the resource ID of the policy assignment that the attestation is setting the state for.
     *
     * @return the policyAssignmentId value
     */
    public String policyAssignmentId() {
        return this.policyAssignmentId;
    }

    /**
     * Set the resource ID of the policy assignment that the attestation is setting the state for.
     *
     * @param policyAssignmentId the policyAssignmentId value to set
     * @return the AttestationInner object itself.
     */
    public AttestationInner withPolicyAssignmentId(String policyAssignmentId) {
        this.policyAssignmentId = policyAssignmentId;
        return this;
    }

    /**
     * Get the policy definition reference ID from a policy set definition that the attestation is setting the state for. If the policy assignment assigns a policy set definition the attestation can choose a definition within the set definition with this property or omit this and set the state for the entire set definition.
     *
     * @return the policyDefinitionReferenceId value
     */
    public String policyDefinitionReferenceId() {
        return this.policyDefinitionReferenceId;
    }

    /**
     * Set the policy definition reference ID from a policy set definition that the attestation is setting the state for. If the policy assignment assigns a policy set definition the attestation can choose a definition within the set definition with this property or omit this and set the state for the entire set definition.
     *
     * @param policyDefinitionReferenceId the policyDefinitionReferenceId value to set
     * @return the AttestationInner object itself.
     */
    public AttestationInner withPolicyDefinitionReferenceId(String policyDefinitionReferenceId) {
        this.policyDefinitionReferenceId = policyDefinitionReferenceId;
        return this;
    }

    /**
     * Get the compliance state that should be set on the resource. Possible values include: 'Compliant', 'NonCompliant', 'Unknown'.
     *
     * @return the complianceState value
     */
    public ComplianceState complianceState() {
        return this.complianceState;
    }

    /**
     * Set the compliance state that should be set on the resource. Possible values include: 'Compliant', 'NonCompliant', 'Unknown'.
     *
     * @param complianceState the complianceState value to set
     * @return the AttestationInner object itself.
     */
    public AttestationInner withComplianceState(ComplianceState complianceState) {
        this.complianceState = complianceState;
        return this;
    }

    /**
     * Get the time the compliance state should expire.
     *
     * @return the expiresOn value
     */
    public DateTime expiresOn() {
        return this.expiresOn;
    }

    /**
     * Set the time the compliance state should expire.
     *
     * @param expiresOn the expiresOn value to set
     * @return the AttestationInner object itself.
     */
    public AttestationInner withExpiresOn(DateTime expiresOn) {
        this.expiresOn = expiresOn;
        return this;
    }

    /**
     * Get the person responsible for setting the state of the resource. This value is typically an Azure Active Directory object ID.
     *
     * @return the owner value
     */
    public String owner() {
        return this.owner;
    }

    /**
     * Set the person responsible for setting the state of the resource. This value is typically an Azure Active Directory object ID.
     *
     * @param owner the owner value to set
     * @return the AttestationInner object itself.
     */
    public AttestationInner withOwner(String owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get comments describing why this attestation was created.
     *
     * @return the comments value
     */
    public String comments() {
        return this.comments;
    }

    /**
     * Set comments describing why this attestation was created.
     *
     * @param comments the comments value to set
     * @return the AttestationInner object itself.
     */
    public AttestationInner withComments(String comments) {
        this.comments = comments;
        return this;
    }

    /**
     * Get the evidence supporting the compliance state set in this attestation.
     *
     * @return the evidence value
     */
    public List<AttestationEvidence> evidence() {
        return this.evidence;
    }

    /**
     * Set the evidence supporting the compliance state set in this attestation.
     *
     * @param evidence the evidence value to set
     * @return the AttestationInner object itself.
     */
    public AttestationInner withEvidence(List<AttestationEvidence> evidence) {
        this.evidence = evidence;
        return this;
    }

    /**
     * Get the status of the attestation.
     *
     * @return the provisioningState value
     */
    public String provisioningState() {
        return this.provisioningState;
    }

    /**
     * Get the time the compliance state was last changed in this attestation.
     *
     * @return the lastComplianceStateChangeAt value
     */
    public DateTime lastComplianceStateChangeAt() {
        return this.lastComplianceStateChangeAt;
    }

    /**
     * Get azure Resource Manager metadata containing createdBy and modifiedBy information.
     *
     * @return the systemData value
     */
    public SystemData systemData() {
        return this.systemData;
    }

}
