// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.billing.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for SpendingLimitStatus. */
public final class SpendingLimitStatus extends ExpandableStringEnum<SpendingLimitStatus> {
    /** Static value Active for SpendingLimitStatus. */
    public static final SpendingLimitStatus ACTIVE = fromString("Active");

    /** Static value Expired for SpendingLimitStatus. */
    public static final SpendingLimitStatus EXPIRED = fromString("Expired");

    /** Static value Reached for SpendingLimitStatus. */
    public static final SpendingLimitStatus REACHED = fromString("Reached");

    /** Static value Removed for SpendingLimitStatus. */
    public static final SpendingLimitStatus REMOVED = fromString("Removed");

    /**
     * Creates or finds a SpendingLimitStatus from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding SpendingLimitStatus.
     */
    @JsonCreator
    public static SpendingLimitStatus fromString(String name) {
        return fromString(name, SpendingLimitStatus.class);
    }

    /** @return known SpendingLimitStatus values. */
    public static Collection<SpendingLimitStatus> values() {
        return values(SpendingLimitStatus.class);
    }
}
